/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CompanyStatus = "active" | "deleted" | "suspended";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MemberRole = "admin" | "member" | "owner";

export type MessageStatus = "delivered" | "failed" | "pending" | "read" | "sent";

export type MessageType = "audio" | "contact" | "document" | "image" | "location" | "reaction" | "sticker" | "text" | "video";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WhatsappConnectionStatus = "banned" | "connected" | "disconnected" | "pending";

export interface Companies {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  max_whatsapp_connections: Generated<number>;
  name: string;
  schema_name: string;
  status: Generated<CompanyStatus>;
  updated_at: Generated<Timestamp>;
}

export interface CompanyMembers {
  company_id: string;
  id: Generated<string>;
  invited_by: string | null;
  joined_at: Generated<Timestamp>;
  permissions: Generated<Json | null>;
  role: Generated<MemberRole>;
  user_id: string;
}

export interface CompanyStats {
  active_users: Generated<number>;
  company_id: string;
  last_message_at: Timestamp | null;
  total_contacts: Generated<number>;
  total_messages: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Invitations {
  accepted_at: Timestamp | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by: string;
  token: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5AuditLogs {
  action: string;
  created_at: Generated<Timestamp>;
  details: Json | null;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  ip_address: string | null;
  user_id: string | null;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5CatalogProducts {
  availability: Generated<string | null>;
  catalog_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string | null>;
  description: string | null;
  id: Generated<string>;
  image_url: string | null;
  name: string;
  price: Numeric | null;
  product_id: string;
  retailer_id: string | null;
  updated_at: Generated<Timestamp>;
  url: string | null;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5ContactAssignments {
  assigned_at: Generated<Timestamp>;
  assigned_by: string;
  assigned_to: string;
  contact_id: string;
  id: Generated<string>;
  unassigned_at: Timestamp | null;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5ContactNotesPrivate {
  contact_id: string;
  content: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5ContactNotesShared {
  author_name: string;
  contact_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5Contacts {
  created_at: Generated<Timestamp>;
  custom_name: string | null;
  id: Generated<string>;
  is_group: Generated<boolean | null>;
  is_online: Generated<boolean>;
  jid: string | null;
  last_seen: Timestamp | null;
  notes_shared: string | null;
  phone_number: string | null;
  profile_picture_url: string | null;
  push_name: string | null;
  updated_at: Generated<Timestamp>;
  whatsapp_connection_id: string | null;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5ContactTags {
  contact_id: string;
  tag_id: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5ConversationStates {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_message_at: Timestamp | null;
  last_message_preview: string | null;
  read_at: Timestamp | null;
  read_by_user_id: string | null;
  unread_count: Generated<number | null>;
  updated_at: Generated<Timestamp>;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5GroupParticipants {
  group_id: string;
  id: Generated<string>;
  is_admin: Generated<boolean | null>;
  joined_at: Generated<Timestamp>;
  participant_jid: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5Groups {
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  jid: string | null;
  name: string | null;
  participant_count: Generated<number | null>;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5MessageReactions {
  created_at: Generated<Timestamp>;
  emoji: string;
  id: Generated<string>;
  message_id: string;
  reactor_jid: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5Messages {
  contact_id: string | null;
  content: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deleted_by_sender: Generated<boolean | null>;
  from_me: boolean;
  id: Generated<string>;
  is_forwarded: Generated<boolean | null>;
  is_starred: Generated<boolean | null>;
  media_mime_type: string | null;
  media_size: number | null;
  media_url: string | null;
  message_id: string | null;
  message_type: MessageType;
  metadata: Json | null;
  quoted_message_id: string | null;
  search_vector: string | null;
  sender_jid: string | null;
  sent_by_user_id: string | null;
  status: Generated<MessageStatus | null>;
  timestamp: Timestamp;
  whatsapp_connection_id: string | null;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5NotificationHistory {
  action_url: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_read: Generated<boolean | null>;
  message: string | null;
  metadata: Json | null;
  notification_type: string;
  read_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5NotificationPreferences {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  muted_contacts: string[] | null;
  quiet_hours_end: string | null;
  quiet_hours_start: string | null;
  sound_choice: Generated<string | null>;
  sound_enabled: Generated<boolean | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5QuickReplies {
  content: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  is_shared: Generated<boolean | null>;
  shortcut: string;
  title: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5StatusUpdates {
  caption: string | null;
  expires_at: Timestamp;
  from_jid: string | null;
  id: Generated<string>;
  media_type: string | null;
  media_url: string | null;
  status_id: string | null;
  timestamp: Timestamp;
  whatsapp_connection_id: string | null;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5Tags {
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5WhatsappCatalogs {
  catalog_id: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string | null;
  product_count: Generated<number | null>;
  synced_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5WhatsappConnections {
  connected_at: Timestamp | null;
  connected_by: string | null;
  connection_order: Generated<number | null>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  jid: string | null;
  last_sync_at: Timestamp | null;
  name: string | null;
  phone_number: string | null;
  status: Generated<WhatsappConnectionStatus>;
  updated_at: Generated<Timestamp>;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5WhatsappLabelAssociations {
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  label_id: string;
  message_id: string | null;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5WhatsappLabels {
  color: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  predefined_id: number | null;
  updated_at: Generated<Timestamp>;
  whatsapp_label_id: string;
}

export interface TenantC2766e1436df43b8Bc972a30193f80f5WhatsmeowLidMappings {
  connection_id: string;
  created_at: Generated<Timestamp>;
  jid: string;
  lid: string;
}

export interface TenantTestFixAuditLogs {
  action: string;
  created_at: Generated<Timestamp>;
  details: Json | null;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  ip_address: string | null;
  user_id: string | null;
}

export interface TenantTestFixCatalogProducts {
  availability: Generated<string | null>;
  catalog_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string | null>;
  description: string | null;
  id: Generated<string>;
  image_url: string | null;
  name: string;
  price: Numeric | null;
  product_id: string;
  retailer_id: string | null;
  updated_at: Generated<Timestamp>;
  url: string | null;
}

export interface TenantTestFixContactAssignments {
  assigned_at: Generated<Timestamp>;
  assigned_by: string;
  assigned_to: string;
  contact_id: string;
  id: Generated<string>;
  unassigned_at: Timestamp | null;
}

export interface TenantTestFixContactNotesPrivate {
  contact_id: string;
  content: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantTestFixContactNotesShared {
  author_name: string;
  contact_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantTestFixContacts {
  created_at: Generated<Timestamp>;
  custom_name: string | null;
  id: Generated<string>;
  is_group: Generated<boolean | null>;
  is_online: Generated<boolean>;
  jid: string | null;
  last_seen: Timestamp | null;
  notes_shared: string | null;
  phone_number: string | null;
  profile_picture_url: string | null;
  push_name: string | null;
  updated_at: Generated<Timestamp>;
  whatsapp_connection_id: string | null;
}

export interface TenantTestFixContactTags {
  contact_id: string;
  tag_id: string;
}

export interface TenantTestFixConversationStates {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_message_at: Timestamp | null;
  last_message_preview: string | null;
  read_at: Timestamp | null;
  read_by_user_id: string | null;
  unread_count: Generated<number | null>;
  updated_at: Generated<Timestamp>;
}

export interface TenantTestFixGroupParticipants {
  group_id: string;
  id: Generated<string>;
  is_admin: Generated<boolean | null>;
  joined_at: Generated<Timestamp>;
  participant_jid: string;
}

export interface TenantTestFixGroups {
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  jid: string | null;
  name: string | null;
  participant_count: Generated<number | null>;
}

export interface TenantTestFixMessageReactions {
  created_at: Generated<Timestamp>;
  emoji: string;
  id: Generated<string>;
  message_id: string;
  reactor_jid: string;
}

export interface TenantTestFixMessages {
  contact_id: string | null;
  content: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deleted_by_sender: Generated<boolean | null>;
  from_me: boolean;
  id: Generated<string>;
  is_forwarded: Generated<boolean | null>;
  is_starred: Generated<boolean | null>;
  media_mime_type: string | null;
  media_size: number | null;
  media_url: string | null;
  message_id: string | null;
  message_type: MessageType;
  metadata: Json | null;
  quoted_message_id: string | null;
  search_vector: string | null;
  sender_jid: string | null;
  sent_by_user_id: string | null;
  status: Generated<MessageStatus | null>;
  timestamp: Timestamp;
  whatsapp_connection_id: string | null;
}

export interface TenantTestFixNotificationHistory {
  action_url: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_read: Generated<boolean | null>;
  message: string | null;
  metadata: Json | null;
  notification_type: string;
  read_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface TenantTestFixNotificationPreferences {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  muted_contacts: string[] | null;
  quiet_hours_end: string | null;
  quiet_hours_start: string | null;
  sound_choice: Generated<string | null>;
  sound_enabled: Generated<boolean | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantTestFixQuickReplies {
  content: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  is_shared: Generated<boolean | null>;
  shortcut: string;
  title: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TenantTestFixStatusUpdates {
  caption: string | null;
  expires_at: Timestamp;
  from_jid: string | null;
  id: Generated<string>;
  media_type: string | null;
  media_url: string | null;
  status_id: string | null;
  timestamp: Timestamp;
  whatsapp_connection_id: string | null;
}

export interface TenantTestFixTags {
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
}

export interface TenantTestFixWhatsappCatalogs {
  catalog_id: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string | null;
  product_count: Generated<number | null>;
  synced_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantTestFixWhatsappConnections {
  connected_at: Timestamp | null;
  connected_by: string | null;
  connection_order: Generated<number | null>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  jid: string | null;
  last_sync_at: Timestamp | null;
  name: string | null;
  phone_number: string | null;
  status: Generated<WhatsappConnectionStatus>;
  updated_at: Generated<Timestamp>;
}

export interface TenantTestFixWhatsappLabelAssociations {
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  label_id: string;
  message_id: string | null;
}

export interface TenantTestFixWhatsappLabels {
  color: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  predefined_id: number | null;
  updated_at: Generated<Timestamp>;
  whatsapp_label_id: string;
}

export interface TenantTestFixWhatsmeowLidMappings {
  connection_id: string;
  created_at: Generated<Timestamp>;
  jid: string;
  lid: string;
}

export interface TenantTestMigrationFixAuditLogs {
  action: string;
  created_at: Generated<Timestamp>;
  details: Json | null;
  entity_id: string | null;
  entity_type: string | null;
  id: Generated<string>;
  ip_address: string | null;
  user_id: string | null;
}

export interface TenantTestMigrationFixCatalogProducts {
  availability: Generated<string | null>;
  catalog_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string | null>;
  description: string | null;
  id: Generated<string>;
  image_url: string | null;
  name: string;
  price: Numeric | null;
  product_id: string;
  retailer_id: string | null;
  updated_at: Generated<Timestamp>;
  url: string | null;
}

export interface TenantTestMigrationFixContactAssignments {
  assigned_at: Generated<Timestamp>;
  assigned_by: string;
  assigned_to: string;
  contact_id: string;
  id: Generated<string>;
  unassigned_at: Timestamp | null;
}

export interface TenantTestMigrationFixContactNotesPrivate {
  contact_id: string;
  content: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantTestMigrationFixContactNotesShared {
  author_name: string;
  contact_id: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantTestMigrationFixContacts {
  created_at: Generated<Timestamp>;
  custom_name: string | null;
  id: Generated<string>;
  is_group: Generated<boolean | null>;
  is_online: Generated<boolean>;
  jid: string | null;
  last_seen: Timestamp | null;
  notes_shared: string | null;
  phone_number: string | null;
  profile_picture_url: string | null;
  push_name: string | null;
  updated_at: Generated<Timestamp>;
  whatsapp_connection_id: string | null;
}

export interface TenantTestMigrationFixContactTags {
  contact_id: string;
  tag_id: string;
}

export interface TenantTestMigrationFixConversationStates {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_message_at: Timestamp | null;
  last_message_preview: string | null;
  read_at: Timestamp | null;
  read_by_user_id: string | null;
  unread_count: Generated<number | null>;
  updated_at: Generated<Timestamp>;
}

export interface TenantTestMigrationFixGroupParticipants {
  group_id: string;
  id: Generated<string>;
  is_admin: Generated<boolean | null>;
  joined_at: Generated<Timestamp>;
  participant_jid: string;
}

export interface TenantTestMigrationFixGroups {
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  jid: string | null;
  name: string | null;
  participant_count: Generated<number | null>;
}

export interface TenantTestMigrationFixMessageReactions {
  created_at: Generated<Timestamp>;
  emoji: string;
  id: Generated<string>;
  message_id: string;
  reactor_jid: string;
}

export interface TenantTestMigrationFixMessages {
  contact_id: string | null;
  content: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deleted_by_sender: Generated<boolean | null>;
  from_me: boolean;
  id: Generated<string>;
  is_forwarded: Generated<boolean | null>;
  is_starred: Generated<boolean | null>;
  media_mime_type: string | null;
  media_size: number | null;
  media_url: string | null;
  message_id: string | null;
  message_type: MessageType;
  metadata: Json | null;
  quoted_message_id: string | null;
  search_vector: string | null;
  sender_jid: string | null;
  sent_by_user_id: string | null;
  status: Generated<MessageStatus | null>;
  timestamp: Timestamp;
  whatsapp_connection_id: string | null;
}

export interface TenantTestMigrationFixNotificationHistory {
  action_url: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_read: Generated<boolean | null>;
  message: string | null;
  metadata: Json | null;
  notification_type: string;
  read_at: Timestamp | null;
  title: string;
  user_id: string;
}

export interface TenantTestMigrationFixNotificationPreferences {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  muted_contacts: string[] | null;
  quiet_hours_end: string | null;
  quiet_hours_start: string | null;
  sound_choice: Generated<string | null>;
  sound_enabled: Generated<boolean | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface TenantTestMigrationFixQuickReplies {
  content: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  is_shared: Generated<boolean | null>;
  shortcut: string;
  title: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface TenantTestMigrationFixStatusUpdates {
  caption: string | null;
  expires_at: Timestamp;
  from_jid: string | null;
  id: Generated<string>;
  media_type: string | null;
  media_url: string | null;
  status_id: string | null;
  timestamp: Timestamp;
  whatsapp_connection_id: string | null;
}

export interface TenantTestMigrationFixTags {
  color: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
}

export interface TenantTestMigrationFixWhatsappCatalogs {
  catalog_id: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string | null;
  product_count: Generated<number | null>;
  synced_at: Timestamp | null;
  updated_at: Generated<Timestamp>;
}

export interface TenantTestMigrationFixWhatsappConnections {
  connected_at: Timestamp | null;
  connected_by: string | null;
  connection_order: Generated<number | null>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  jid: string | null;
  last_sync_at: Timestamp | null;
  name: string | null;
  phone_number: string | null;
  status: Generated<WhatsappConnectionStatus>;
  updated_at: Generated<Timestamp>;
}

export interface TenantTestMigrationFixWhatsappLabelAssociations {
  contact_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  label_id: string;
  message_id: string | null;
}

export interface TenantTestMigrationFixWhatsappLabels {
  color: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  predefined_id: number | null;
  updated_at: Generated<Timestamp>;
  whatsapp_label_id: string;
}

export interface TenantTestMigrationFixWhatsmeowLidMappings {
  connection_id: string;
  created_at: Generated<Timestamp>;
  jid: string;
  lid: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  name: string | null;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface UserSessions {
  created_at: Generated<Timestamp>;
  device_name: string | null;
  device_type: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  last_active_at: Generated<Timestamp>;
  refresh_token: string;
  user_agent: string | null;
  user_id: string;
}

export interface WhatsappSessionsWhatsmeowAppStateMutationMacs {
  connection_id: string;
  index_mac: Buffer;
  jid: string;
  name: string;
  value_mac: Buffer;
  version: Int8;
}

export interface WhatsappSessionsWhatsmeowAppStateSyncKeys {
  connection_id: string;
  fingerprint: Buffer;
  jid: string;
  key_data: Buffer;
  key_id: Buffer;
  timestamp: Int8;
}

export interface WhatsappSessionsWhatsmeowAppStateVersion {
  connection_id: string;
  hash: Buffer;
  jid: string;
  name: string;
  version: Int8;
}

export interface WhatsappSessionsWhatsmeowChatSettings {
  archived: Generated<boolean>;
  chat_jid: string;
  connection_id: string;
  muted_until: Generated<Int8>;
  our_jid: string;
  pinned: Generated<boolean>;
}

export interface WhatsappSessionsWhatsmeowContacts {
  business_name: string | null;
  connection_id: string;
  first_name: string | null;
  full_name: string | null;
  our_jid: string;
  push_name: string | null;
  their_jid: string;
}

export interface WhatsappSessionsWhatsmeowDevice {
  adv_account_sig: Buffer;
  adv_details: Buffer;
  adv_device_sig: Buffer;
  adv_key: Buffer;
  business_name: Generated<string>;
  connection_id: string;
  facebook_uuid: string | null;
  identity_key: Buffer;
  jid: string;
  noise_key: Buffer;
  platform: Generated<string>;
  push_name: Generated<string>;
  registration_id: Int8;
  signed_pre_key: Buffer;
  signed_pre_key_id: number;
  signed_pre_key_sig: Buffer;
}

export interface WhatsappSessionsWhatsmeowIdentityKeys {
  connection_id: string;
  identity: Buffer;
  our_jid: string;
  their_id: string;
}

export interface WhatsappSessionsWhatsmeowLidMappings {
  connection_id: string;
  created_at: Generated<Timestamp>;
  jid: string;
  lid: string;
}

export interface WhatsappSessionsWhatsmeowMessageSecrets {
  chat_jid: string;
  connection_id: string;
  message_id: string;
  our_jid: string;
  secret: Buffer;
  sender_jid: string;
}

export interface WhatsappSessionsWhatsmeowPreKeys {
  connection_id: string;
  jid: string;
  key: Buffer;
  key_id: number;
  uploaded: Generated<boolean>;
}

export interface WhatsappSessionsWhatsmeowPrivacyTokens {
  connection_id: string;
  our_jid: string;
  timestamp: Int8;
  token: Buffer;
  user_jid: string;
}

export interface WhatsappSessionsWhatsmeowSenderKeys {
  chat_id: string;
  connection_id: string;
  our_jid: string;
  sender_id: string;
  sender_key: Buffer;
}

export interface WhatsappSessionsWhatsmeowSessions {
  connection_id: string;
  our_jid: string;
  session: Buffer;
  their_id: string;
}

export interface WhatsappSessionsWhatsmeowVersion {
  connection_id: string;
  version: number;
}

export interface DB {
  companies: Companies;
  company_members: CompanyMembers;
  company_stats: CompanyStats;
  invitations: Invitations;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.audit_logs": TenantC2766e1436df43b8Bc972a30193f80f5AuditLogs;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.catalog_products": TenantC2766e1436df43b8Bc972a30193f80f5CatalogProducts;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.contact_assignments": TenantC2766e1436df43b8Bc972a30193f80f5ContactAssignments;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.contact_notes_private": TenantC2766e1436df43b8Bc972a30193f80f5ContactNotesPrivate;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.contact_notes_shared": TenantC2766e1436df43b8Bc972a30193f80f5ContactNotesShared;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.contact_tags": TenantC2766e1436df43b8Bc972a30193f80f5ContactTags;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.contacts": TenantC2766e1436df43b8Bc972a30193f80f5Contacts;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.conversation_states": TenantC2766e1436df43b8Bc972a30193f80f5ConversationStates;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.group_participants": TenantC2766e1436df43b8Bc972a30193f80f5GroupParticipants;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.groups": TenantC2766e1436df43b8Bc972a30193f80f5Groups;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.message_reactions": TenantC2766e1436df43b8Bc972a30193f80f5MessageReactions;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.messages": TenantC2766e1436df43b8Bc972a30193f80f5Messages;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.notification_history": TenantC2766e1436df43b8Bc972a30193f80f5NotificationHistory;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.notification_preferences": TenantC2766e1436df43b8Bc972a30193f80f5NotificationPreferences;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.quick_replies": TenantC2766e1436df43b8Bc972a30193f80f5QuickReplies;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.status_updates": TenantC2766e1436df43b8Bc972a30193f80f5StatusUpdates;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.tags": TenantC2766e1436df43b8Bc972a30193f80f5Tags;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.whatsapp_catalogs": TenantC2766e1436df43b8Bc972a30193f80f5WhatsappCatalogs;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.whatsapp_connections": TenantC2766e1436df43b8Bc972a30193f80f5WhatsappConnections;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.whatsapp_label_associations": TenantC2766e1436df43b8Bc972a30193f80f5WhatsappLabelAssociations;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.whatsapp_labels": TenantC2766e1436df43b8Bc972a30193f80f5WhatsappLabels;
  "tenant_c2766e14_36df_43b8_bc97_2a30193f80f5.whatsmeow_lid_mappings": TenantC2766e1436df43b8Bc972a30193f80f5WhatsmeowLidMappings;
  "tenant_test_fix.audit_logs": TenantTestFixAuditLogs;
  "tenant_test_fix.catalog_products": TenantTestFixCatalogProducts;
  "tenant_test_fix.contact_assignments": TenantTestFixContactAssignments;
  "tenant_test_fix.contact_notes_private": TenantTestFixContactNotesPrivate;
  "tenant_test_fix.contact_notes_shared": TenantTestFixContactNotesShared;
  "tenant_test_fix.contact_tags": TenantTestFixContactTags;
  "tenant_test_fix.contacts": TenantTestFixContacts;
  "tenant_test_fix.conversation_states": TenantTestFixConversationStates;
  "tenant_test_fix.group_participants": TenantTestFixGroupParticipants;
  "tenant_test_fix.groups": TenantTestFixGroups;
  "tenant_test_fix.message_reactions": TenantTestFixMessageReactions;
  "tenant_test_fix.messages": TenantTestFixMessages;
  "tenant_test_fix.notification_history": TenantTestFixNotificationHistory;
  "tenant_test_fix.notification_preferences": TenantTestFixNotificationPreferences;
  "tenant_test_fix.quick_replies": TenantTestFixQuickReplies;
  "tenant_test_fix.status_updates": TenantTestFixStatusUpdates;
  "tenant_test_fix.tags": TenantTestFixTags;
  "tenant_test_fix.whatsapp_catalogs": TenantTestFixWhatsappCatalogs;
  "tenant_test_fix.whatsapp_connections": TenantTestFixWhatsappConnections;
  "tenant_test_fix.whatsapp_label_associations": TenantTestFixWhatsappLabelAssociations;
  "tenant_test_fix.whatsapp_labels": TenantTestFixWhatsappLabels;
  "tenant_test_fix.whatsmeow_lid_mappings": TenantTestFixWhatsmeowLidMappings;
  "tenant_test_migration_fix.audit_logs": TenantTestMigrationFixAuditLogs;
  "tenant_test_migration_fix.catalog_products": TenantTestMigrationFixCatalogProducts;
  "tenant_test_migration_fix.contact_assignments": TenantTestMigrationFixContactAssignments;
  "tenant_test_migration_fix.contact_notes_private": TenantTestMigrationFixContactNotesPrivate;
  "tenant_test_migration_fix.contact_notes_shared": TenantTestMigrationFixContactNotesShared;
  "tenant_test_migration_fix.contact_tags": TenantTestMigrationFixContactTags;
  "tenant_test_migration_fix.contacts": TenantTestMigrationFixContacts;
  "tenant_test_migration_fix.conversation_states": TenantTestMigrationFixConversationStates;
  "tenant_test_migration_fix.group_participants": TenantTestMigrationFixGroupParticipants;
  "tenant_test_migration_fix.groups": TenantTestMigrationFixGroups;
  "tenant_test_migration_fix.message_reactions": TenantTestMigrationFixMessageReactions;
  "tenant_test_migration_fix.messages": TenantTestMigrationFixMessages;
  "tenant_test_migration_fix.notification_history": TenantTestMigrationFixNotificationHistory;
  "tenant_test_migration_fix.notification_preferences": TenantTestMigrationFixNotificationPreferences;
  "tenant_test_migration_fix.quick_replies": TenantTestMigrationFixQuickReplies;
  "tenant_test_migration_fix.status_updates": TenantTestMigrationFixStatusUpdates;
  "tenant_test_migration_fix.tags": TenantTestMigrationFixTags;
  "tenant_test_migration_fix.whatsapp_catalogs": TenantTestMigrationFixWhatsappCatalogs;
  "tenant_test_migration_fix.whatsapp_connections": TenantTestMigrationFixWhatsappConnections;
  "tenant_test_migration_fix.whatsapp_label_associations": TenantTestMigrationFixWhatsappLabelAssociations;
  "tenant_test_migration_fix.whatsapp_labels": TenantTestMigrationFixWhatsappLabels;
  "tenant_test_migration_fix.whatsmeow_lid_mappings": TenantTestMigrationFixWhatsmeowLidMappings;
  user_sessions: UserSessions;
  users: Users;
  "whatsapp_sessions.whatsmeow_app_state_mutation_macs": WhatsappSessionsWhatsmeowAppStateMutationMacs;
  "whatsapp_sessions.whatsmeow_app_state_sync_keys": WhatsappSessionsWhatsmeowAppStateSyncKeys;
  "whatsapp_sessions.whatsmeow_app_state_version": WhatsappSessionsWhatsmeowAppStateVersion;
  "whatsapp_sessions.whatsmeow_chat_settings": WhatsappSessionsWhatsmeowChatSettings;
  "whatsapp_sessions.whatsmeow_contacts": WhatsappSessionsWhatsmeowContacts;
  "whatsapp_sessions.whatsmeow_device": WhatsappSessionsWhatsmeowDevice;
  "whatsapp_sessions.whatsmeow_identity_keys": WhatsappSessionsWhatsmeowIdentityKeys;
  "whatsapp_sessions.whatsmeow_lid_mappings": WhatsappSessionsWhatsmeowLidMappings;
  "whatsapp_sessions.whatsmeow_message_secrets": WhatsappSessionsWhatsmeowMessageSecrets;
  "whatsapp_sessions.whatsmeow_pre_keys": WhatsappSessionsWhatsmeowPreKeys;
  "whatsapp_sessions.whatsmeow_privacy_tokens": WhatsappSessionsWhatsmeowPrivacyTokens;
  "whatsapp_sessions.whatsmeow_sender_keys": WhatsappSessionsWhatsmeowSenderKeys;
  "whatsapp_sessions.whatsmeow_sessions": WhatsappSessionsWhatsmeowSessions;
  "whatsapp_sessions.whatsmeow_version": WhatsappSessionsWhatsmeowVersion;
}
