/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CompanyStatus = "active" | "deleted" | "suspended";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MemberRole = "admin" | "member" | "owner";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Companies {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  max_whatsapp_connections: Generated<number>;
  name: string;
  schema_name: string;
  status: Generated<CompanyStatus>;
  updated_at: Generated<Timestamp>;
}

export interface CompanyMembers {
  company_id: string;
  id: Generated<string>;
  invited_by: string | null;
  joined_at: Generated<Timestamp>;
  permissions: Generated<Json | null>;
  role: Generated<MemberRole>;
  user_id: string;
}

export interface CompanyStats {
  active_users: Generated<number>;
  company_id: string;
  last_message_at: Timestamp | null;
  total_contacts: Generated<number>;
  total_messages: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Invitations {
  accepted_at: Timestamp | null;
  company_id: string;
  created_at: Generated<Timestamp>;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by: string;
  token: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  name: string | null;
  password_hash: string;
  updated_at: Generated<Timestamp>;
}

export interface UserSessions {
  created_at: Generated<Timestamp>;
  device_name: string | null;
  device_type: string | null;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  last_active_at: Generated<Timestamp>;
  refresh_token: string;
  user_agent: string | null;
  user_id: string;
}

export interface WhatsappSessionsWhatsmeowAppStateMutationMacs {
  connection_id: string;
  index_mac: Buffer;
  jid: string;
  name: string;
  value_mac: Buffer;
  version: Int8;
}

export interface WhatsappSessionsWhatsmeowAppStateSyncKeys {
  connection_id: string;
  fingerprint: Buffer;
  jid: string;
  key_data: Buffer;
  key_id: Buffer;
  timestamp: Int8;
}

export interface WhatsappSessionsWhatsmeowAppStateVersion {
  connection_id: string;
  hash: Buffer;
  jid: string;
  name: string;
  version: Int8;
}

export interface WhatsappSessionsWhatsmeowChatSettings {
  archived: Generated<boolean>;
  chat_jid: string;
  connection_id: string;
  muted_until: Generated<Int8>;
  our_jid: string;
  pinned: Generated<boolean>;
}

export interface WhatsappSessionsWhatsmeowContacts {
  business_name: string | null;
  connection_id: string;
  first_name: string | null;
  full_name: string | null;
  our_jid: string;
  push_name: string | null;
  their_jid: string;
}

export interface WhatsappSessionsWhatsmeowDevice {
  adv_account_sig: Buffer;
  adv_details: Buffer;
  adv_device_sig: Buffer;
  adv_key: Buffer;
  business_name: Generated<string>;
  connection_id: string;
  facebook_uuid: string | null;
  identity_key: Buffer;
  jid: string;
  noise_key: Buffer;
  platform: Generated<string>;
  push_name: Generated<string>;
  registration_id: Int8;
  signed_pre_key: Buffer;
  signed_pre_key_id: number;
  signed_pre_key_sig: Buffer;
}

export interface WhatsappSessionsWhatsmeowIdentityKeys {
  connection_id: string;
  identity: Buffer;
  our_jid: string;
  their_id: string;
}

export interface WhatsappSessionsWhatsmeowLidMappings {
  connection_id: string;
  created_at: Generated<Timestamp>;
  jid: string;
  lid: string;
}

export interface WhatsappSessionsWhatsmeowMessageSecrets {
  chat_jid: string;
  connection_id: string;
  message_id: string;
  our_jid: string;
  secret: Buffer;
  sender_jid: string;
}

export interface WhatsappSessionsWhatsmeowPreKeys {
  connection_id: string;
  jid: string;
  key: Buffer;
  key_id: number;
  uploaded: Generated<boolean>;
}

export interface WhatsappSessionsWhatsmeowPrivacyTokens {
  connection_id: string;
  our_jid: string;
  timestamp: Int8;
  token: Buffer;
  user_jid: string;
}

export interface WhatsappSessionsWhatsmeowSenderKeys {
  chat_id: string;
  connection_id: string;
  our_jid: string;
  sender_id: string;
  sender_key: Buffer;
}

export interface WhatsappSessionsWhatsmeowSessions {
  connection_id: string;
  our_jid: string;
  session: Buffer;
  their_id: string;
}

export interface WhatsappSessionsWhatsmeowVersion {
  connection_id: string;
  version: number;
}

export interface DB {
  companies: Companies;
  company_members: CompanyMembers;
  company_stats: CompanyStats;
  invitations: Invitations;
  user_sessions: UserSessions;
  users: Users;
  "whatsapp_sessions.whatsmeow_app_state_mutation_macs": WhatsappSessionsWhatsmeowAppStateMutationMacs;
  "whatsapp_sessions.whatsmeow_app_state_sync_keys": WhatsappSessionsWhatsmeowAppStateSyncKeys;
  "whatsapp_sessions.whatsmeow_app_state_version": WhatsappSessionsWhatsmeowAppStateVersion;
  "whatsapp_sessions.whatsmeow_chat_settings": WhatsappSessionsWhatsmeowChatSettings;
  "whatsapp_sessions.whatsmeow_contacts": WhatsappSessionsWhatsmeowContacts;
  "whatsapp_sessions.whatsmeow_device": WhatsappSessionsWhatsmeowDevice;
  "whatsapp_sessions.whatsmeow_identity_keys": WhatsappSessionsWhatsmeowIdentityKeys;
  "whatsapp_sessions.whatsmeow_lid_mappings": WhatsappSessionsWhatsmeowLidMappings;
  "whatsapp_sessions.whatsmeow_message_secrets": WhatsappSessionsWhatsmeowMessageSecrets;
  "whatsapp_sessions.whatsmeow_pre_keys": WhatsappSessionsWhatsmeowPreKeys;
  "whatsapp_sessions.whatsmeow_privacy_tokens": WhatsappSessionsWhatsmeowPrivacyTokens;
  "whatsapp_sessions.whatsmeow_sender_keys": WhatsappSessionsWhatsmeowSenderKeys;
  "whatsapp_sessions.whatsmeow_sessions": WhatsappSessionsWhatsmeowSessions;
  "whatsapp_sessions.whatsmeow_version": WhatsappSessionsWhatsmeowVersion;
}
