// Re-export types from shared package for convenience
export type {
  CompanyMemberRole,
  CompanyStatus,
  MessageStatus,
  MessageType,
  ScheduledMessageStatus,
} from "@wateaminbox/shared";
export type {
  ApiRateLimitBucketsTable,
  AuditLogsTable,
  AuthTokensTable,
  AuthTokenType,
  BulkConnectionBudgetsTable,
  BulkJobsTable,
  CatalogProductsTable,
  CatalogStatus,
  // Public schema types
  CompaniesTable,
  CompanyMembersTable,
  CompanyStatsTable,
  ContactAssignmentsTable,
  ContactNotesPrivateTable,
  ContactNotesSharedTable,
  ContactsTable,
  ContactTagsTable,
  ConversationCaseKind,
  ConversationCaseOpenSource,
  ConversationCaseResolutionOutcome,
  ConversationCaseStatus,
  ConversationCasesTable,
  ConversationStatesTable,
  ConversationStatus,
  Database,
  GroupParticipantsTable,
  GroupsTable,
  InvitationsTable,
  /** @deprecated Use CompanyMemberRole from @wateaminbox/shared instead */
  MemberRole,
  MessageReactionsTable,
  NotificationHistoryTable,
  NotificationPreferencesTable,
  NotificationType,
  ProductVisibility,
  PurgeCleanupItemsTable,
  PurgeCleanupKind,
  QuickRepliesTable,
  ScheduledMessagesTable,
  SlaPoliciesTable,
  StatusUpdatesTable,
  TagsTable,
  TenantDatabase,
  TenantMessagesTable,
  UserSessionsTable,
  UsersTable,
  WhatsAppCatalogsTable,
  WhatsAppConnectionStatus,
  // Tenant schema types
  WhatsAppConnectionsTable,
  WhatsAppLabelsTable,
} from "./client";
export {
  createDatabase,
  createTenantDatabase,
  db,
  getTenantSchemaName,
} from "./client";
export type {
  DuplicateBlocker,
  TenantIndexPreflightRow,
  TenantIndexReconcileResult,
  TenantIndexTarget,
} from "./tenant-index-names";
export {
  dropLegacyLabelUniqueIndex,
  formatDuplicateBlockers,
  formatPreflightReport,
  legacyIdentifier,
  PG_IDENTIFIER_MAX_BYTES,
  preflightTenantIndexNames,
  reconcileTenantIndexNames,
  renameTenantRelation,
  TENANT_INDEX_TARGETS,
  TENANT_SCHEMA_NAME_LENGTH,
  TENANT_SUFFIX_BUDGET,
  targetIdentifier,
} from "./tenant-index-names";
export type { TenantSchemaContractIsComplete } from "./tenant-schema";
export {
  reconcileTenantSchema,
  TENANT_SCHEMA_CONTRACT,
} from "./tenant-schema";
