// Re-export types from shared package for convenience
export type {
  CompanyMemberRole,
  CompanyStatus,
  MessageStatus,
  MessageType,
  ScheduledMessageStatus,
} from "@wateaminbox/shared";
export type {
  ApiRateLimitBucketsTable,
  ApiTokenScope,
  ApiTokensTable,
  AuditLogsTable,
  AuthTokensTable,
  AuthTokenType,
  AutoReplySettingsTable,
  BulkConnectionBudgetsTable,
  BulkJobsTable,
  ChannelFanoutKind,
  ChannelIngressRoutesTable,
  ChannelIngressRouteState,
  ChannelMessageDeliveryOutboxTable,
  ChannelSpineWorkspaceFlagAuditTable,
  ChannelSpineWorkspaceFlagsTable,
  ChannelSpineWriteAuthority,
  CatalogProductsTable,
  CatalogStatus,
  ChannelAccountCapabilitiesTable,
  ChannelAccountsTable,
  ChannelAccountStatus,
  ChannelEventInboxTable,
  ChannelSpineBackfillCheckpointsTable,
  ChannelSpineReconciliationJournalTable,
  // Public schema types
  CompaniesTable,
  CompanyMembersTable,
  CompanyStatsTable,
  ContactAssignmentsTable,
  ContactEndpointReassignmentEventsTable,
  ContactEndpointsTable,
  ContactMergeEventsTable,
  ContactNotesPrivateTable,
  ContactNotesSharedTable,
  ContactsTable,
  ContactSuppressionsTable,
  ContactTagsTable,
  ConversationCaseKind,
  ConversationCaseOpenSource,
  ConversationCaseResolutionOutcome,
  ConversationCaseStatus,
  ConversationCasesTable,
  ConversationParticipantsTable,
  ConversationsTable,
  ConversationStatesTable,
  ConversationStatus,
  ConversationSyncStatesTable,
  ConversationTagsTable,
  Database,
  EndpointAccountStatesTable,
  EndpointPresenceTable,
  GroupParticipantsTable,
  GroupsTable,
  InvitationsTable,
  /** @deprecated Use CompanyMemberRole from @wateaminbox/shared instead */
  MemberRole,
  MessageAttachmentsTable,
  MessageDeliveryEventsTable,
  MessageParticipantsTable,
  MessageReactionsTable,
  NotificationHistoryTable,
  NotificationPreferencesTable,
  NotificationType,
  OutboundIntentAttachmentsTable,
  OutboundMessageIntentsTable,
  ProductVisibility,
  PurgeCleanupItemsTable,
  PurgeCleanupKind,
  QuickRepliesTable,
  RetiredRefreshToken,
  ScheduledMessagesTable,
  SlaPoliciesTable,
  StatusUpdatesTable,
  TagsTable,
  TenantDatabase,
  TenantMessagesTable,
  UserSessionsTable,
  UsersTable,
  WhatsAppCatalogsTable,
  WhatsAppConnectionStatus,
  // Tenant schema types
  WhatsAppAttachmentFetchStateTable,
  WhatsAppConnectionsTable,
  WhatsAppLabelsTable,
} from "./client";
export {
  createDatabase,
  createTenantDatabase,
  db,
  getTenantSchemaName,
} from "./client";
export type { ChannelSpineIndexResult } from "./channel-spine-index-runner";
export { reconcileChannelSpineConcurrentIndexes } from "./channel-spine-index-runner";
export { ensureChannelSpineTenantSchema } from "./channel-spine-schema";
export type {
  DuplicateBlocker,
  TenantIndexPreflightRow,
  TenantIndexReconcileResult,
  TenantIndexTarget,
} from "./tenant-index-names";
export {
  dropLegacyLabelUniqueIndex,
  formatDuplicateBlockers,
  formatPreflightReport,
  legacyIdentifier,
  PG_IDENTIFIER_MAX_BYTES,
  preflightTenantIndexNames,
  reconcileTenantIndexNames,
  renameTenantRelation,
  TENANT_INDEX_TARGETS,
  TENANT_SCHEMA_NAME_LENGTH,
  TENANT_SUFFIX_BUDGET,
  targetIdentifier,
} from "./tenant-index-names";
export type { TenantSchemaContractIsComplete } from "./tenant-schema";
export {
  reconcileTenantSchema,
  TENANT_SCHEMA_CONTRACT,
} from "./tenant-schema";
